apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        tier: nodejs
    spec:
      containers:
        - name: hello
          image: gcr.io/vpnproject1-318209/appk8s@sha256:f7bc77885ccdbd7f47cca284a63701d56f70de47a0b1dec88c83bc1c0588ea7a
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: nodejs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        tier: nodejs
    spec:
      containers:
        - name: hello
          image: gcr.io/vpnproject1-318209/appk8s@sha256:f7bc77885ccdbd7f47cca284a63701d56f70de47a0b1dec88c83bc1c0588ea7a
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: nodejs
    tier: nodejs
  type: LoadBalancer