apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: rococoshka/frontendk8s:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: frontend-docker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
        - name: backend
          image: rococoshka/backendk8s:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: backend-docker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        tier: db
    spec:
      containers:
        - name: db
          image: postgres:11.6-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: database-docker
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  externalName: backend
  selector:
    app: backend
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  externalName: db
  selector:
    app: db
    tier: db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: frontend
    tier: frontend
  type: LoadBalancer